import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Footer from '../layout/Footer'
import Header from '../layout/Header'

export default function Users() {
  return (
    // className={styles.container}
    <div >
      <Head>
        <title>InfluxIQ | Home </title>
        <meta key="og:image" name="og:image" content="https://all-frontend-assets.s3.amazonaws.com/transcendentpagan/assets/images/og_image.jpg" />
        <meta property="og:url" content="https://next.influxhostserver.com" key="ogurl" />
        <meta property="og:site_name" content="Influiq" key="ogsitename" />
        <meta property="og:title" content="Next React" key="ogtitle" />
        <meta property="og:description" content="Generated by create next app" key="ogdesc" />
      </Head>

      <Header />

      <Footer />
    </div>
  )
}
