import React from 'react'
import Head from 'next/head'

export default function about() {
    return (
        <>
            <Head>
                <title>InfluxIq | About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div ><center>
                <h1>About Page</h1>
                <p>
                    This is test about page.
                </p></center><br />
            </div>
        </>
    )
}
