import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from './layout/Footer'
import Header from './layout/Header'
import Container from '@material-ui/core/Container'
import Box from '@material-ui/core/Box'
import { Typography } from '@mui/material'
// import useStyles from '../styles/homePage';
import stylesv from '../styles/indexPage.module.css'

// import { makeStyles } from '@mui/styles';

// const useStyles = makeStyles({
//   wrap: {
//     backgroundColor: '#F9F9F9',
//     marginTop: 60,
//   },
// });

export default function Home() {

  // const classes = useStyles();

  return (
    <Container className={styles.container}>
      <Head>
        <title>InfluxIQ | Home </title>
        <meta key="og:image" name="og:image" content="https://all-frontend-assets.s3.amazonaws.com/transcendentpagan/assets/images/og_image.jpg" />
        <meta property="og:url" content="https://next.influxhostserver.com" key="ogurl" />
        <meta property="og:site_name" content="Influiq" key="ogsitename" />
        <meta property="og:title" content="Next React" key="ogtitle" />
        <meta property="og:description" content="Generated by create next app" key="ogdesc" />
      </Head>

      <div className={stylesv.wrap}>
        <center><Image
          src="/testImg.jpg"
          alt="Picture of the author"
          width={380}
          height={250}
          className={stylesv.img}
        /></center>
        <Typography variant='body1' className={stylesv.lorem}>{"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum"}</Typography>
      </div>

    </Container>
  )
}
